#!/usr/bin/env python3
"""
Embed the real corpus with bge-small-en-v1.5.

This is Phase 2 work arriving early: the interactive demos need real dense
retrieval, and synthesising it is not an option. Embeddings are written to
data/corpus/embeddings/ (gitignored, ~79 MB) and regenerated by this script.

    python3 harness/interactive/embed.py
    python3 harness/interactive/embed.py --strategy section-aware

Resumable: an existing .npy matching the current chunk count is reused.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
CHUNKS = ROOT / "data" / "corpus" / "chunks"
EMB = ROOT / "data" / "corpus" / "embeddings"
MODEL = "BAAI/bge-small-en-v1.5"
BATCH = 64


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--strategy", default="fixed-512")
    ap.add_argument("--batch", type=int, default=BATCH)
    args = ap.parse_args()

    src = CHUNKS / f"{args.strategy}.jsonl"
    ids, texts = [], []
    with open(src) as f:
        for line in f:
            c = json.loads(line)
            ids.append(c["chunk_id"])
            texts.append(c["text"])
    print(f"  {len(texts):,} chunks from {src.name}")

    EMB.mkdir(parents=True, exist_ok=True)
    vec_path = EMB / f"{args.strategy}.npy"
    id_path = EMB / f"{args.strategy}.ids.json"
    if vec_path.exists() and id_path.exists():
        existing = json.loads(id_path.read_text())
        if existing == ids:
            print(f"  {vec_path.name} already matches this chunk set — nothing to do")
            return 0
        print("  existing embeddings do not match the current chunks — recomputing")

    import torch
    from transformers import AutoTokenizer, AutoModel, logging as hf
    hf.set_verbosity_error()

    dev = "cuda" if torch.cuda.is_available() else "cpu"
    tok = AutoTokenizer.from_pretrained(MODEL)
    model = AutoModel.from_pretrained(MODEL)
    if dev == "cuda":
        model = model.half()
    model = model.to(dev).eval()
    print(f"  {MODEL} on {dev}")

    out = np.zeros((len(texts), 384), dtype=np.float32)
    t0 = time.time()
    with torch.inference_mode():
        for i in range(0, len(texts), args.batch):
            enc = tok(texts[i:i + args.batch], padding=True, truncation=True,
                      max_length=512, return_tensors="pt").to(dev)
            # bge uses the CLS token, then L2 normalisation, so a dot product
            # is cosine similarity.
            h = model(**enc).last_hidden_state[:, 0]
            h = torch.nn.functional.normalize(h, dim=-1)
            out[i:i + h.shape[0]] = h.float().cpu().numpy()
            if (i // args.batch) % 100 == 0 and i:
                rate = i / (time.time() - t0)
                print(f"    {i:,}/{len(texts):,}  {rate:.0f}/s  "
                      f"eta {(len(texts)-i)/rate/60:.1f} min", flush=True)

    np.save(vec_path, out)
    id_path.write_text(json.dumps(ids))
    dt = time.time() - t0
    print(f"  wrote {vec_path.name} {out.shape} in {dt/60:.1f} min "
          f"({len(texts)/dt:.0f} chunks/s, {vec_path.stat().st_size/1e6:.0f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
